[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "asyncio>=3.4.3",
    "flask>=3.1.1",
    "numpy>=2.3.2",
    "python-telegram-bot>=22.3",
    "requests>=2.32.4",
    "scikit-learn>=1.7.1",
]
